#+TITLE: Algoritmo genético para Mochila Binária
#+SUBTITLE: Algoritmos Bioinspirados
#+AUTHOR: Heitor Lourenço Werneck
#+EMAIL: heitorwerneck@hotmail.com
#+DATE: 
#+LANGUAGE: pt
#+OPTIONS: ^:nil email:nil author:nil toc:nil
#+LATEX_HEADER: \author{Heitor Lourenço Werneck \\github.com/heitor57\\{\href{mailto:heitorwerneck@hotmail.com}{heitorwerneck@hotmail.com}}}
#+LATEX_HEADER: \usepackage[AUTO]{babel}
# mathtools ja inclui amsmath #+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \usepackage[binary-units=true]{siunitx}
#+LATEX_HEADER: \usepackage[top=0.5cm,bottom=1.5cm,left=2cm,right=2cm]{geometry}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{algpseudocode}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage[Algoritmo]{algorithm}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{colortbl}
#+LATEX_HEADER: \usepackage{graphicx,wrapfig,lipsum}
#+LATEX_HEADER: \usepackage{pifont}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{rotating}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{tablefootnote}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \usepackage{natbib}
#+LATEX_HEADER: \usepackage{dblfloatfix}
#+LATEX_HEADER: \usepackage{color, colortbl}
#+LATEX_HEADER: \usepackage{chngcntr}
#+LATEX_HEADER: \usepackage{epstopdf}
#+LATEX_HEADER: \usepackage{comment}
#+LATEX_HEADER: \usepackage{float}

#+latex_class_options: [11pt]

#+PROPERTY: header-args :eval no-export
#+BEGIN_EXPORT latex
\usetikzlibrary{arrows, fit, matrix, positioning, shapes, backgrounds,intersections}
\usetikzlibrary{decorations.pathreplacing}
\usetikzlibrary{automata, positioning, arrows}
\usetikzlibrary{calc}

\definecolor{bg}{rgb}{0.95,0.95,0.95}
\BeforeBeginEnvironment{minted}{\begin{mdframed}[backgroundcolor=bg]}
\AfterEndEnvironment{minted}{\end{mdframed}}
\numberwithin{equation}{section}
\algnewcommand{\IfThenElse}[3]{% \IfThenElse{<if>}{<then>}{<else>}
  \State \algorithmicif\ #1\ \algorithmicthen\ #2\ \algorithmicelse\ #3}

% Define block styles
\tikzstyle{decision} = [diamond, draw, fill=blue!20, 
    text width=4.5em, text badly centered, node distance=3cm, inner sep=0pt]
\tikzstyle{block} = [rectangle, draw, fill=blue!20, 
    text width=5em, text centered, rounded corners, minimum height=4em]
\tikzstyle{line} = [draw, -latex']
\tikzstyle{cloud} = [ellipse, draw, fill=red!20, 
    text width=5em, text centered, rounded corners, minimum height=2em]
%\tikzstyle{cloud} = [draw, ellipse,fill=red!20, node distance=3.5cm,
%    minimum height=2em]


\lstset{
  basicstyle=\ttfamily,
  columns=fullflexible,
  frame=single,
  breaklines=true,
  postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space},
}
\DeclarePairedDelimiter\ceil{\lceil}{\rceil}
\DeclarePairedDelimiter\floor{\lfloor}{\rfloor}

% Numbering fix
\counterwithout{equation}{section} % undo numbering system provided by phstyle.cls
%\counterwithin{equation}{chapter}  % implement desired numbering system
	
\definecolor{Gray}{gray}{0.9}
#+END_EXPORT


* Introdução
Algoritmos genéticos se referem a uma família de modelos computacionais inspirados na evolução(seleção natural e genética). Esses algoritmos representam a solução problema atráves de estruturas semelhantes a cromossomos e aplicam operadores de recombinação para preservar os dados/informações vitais cite:whitley94_genet_algor_tutor,goldenberg1989genetic. Normalmente um algoritmo genético será baseado em população e usará operadores de seleção e recombinação para buscar uma solução no espaço de busca cite:whitley94_genet_algor_tutor.

Algoritmos genéticos são utilizados em diversos cenários pela natureza generalista de seu modelo, como por exemplo: sistemas de recomendação cite:naruchitparames2011friend,silva2010graph; visão computacional cite:gong2004quadtree; robôs de limpeza cite:yakoubi2016path; recuperação de informação cite:vrajitoru1998crossover e agendamento de voos cite:lee2007multi.

Os algoritmos genéticos também possuem a capacidade de fazer /exploitation/ e /exploration/ que são características de modelos estado da arte em diversas áreas, como por exemplo: /Multi-Armed Bandits/; Nuvem de partículas e outros. Uma característica extremamente importante para diversos cenários.

Esse trabalho consiste na implementação e análise de um algoritmo genético para a solução do problema da mochila binária, sendo este um problema combinatório.

* Problema
Nesse problema temos $n$ itens, cada um com um valor de utilidade $u_i$ e peso $w_i$, o objetivo é maximizar $\sum_{i=0}^{n-1}u_i$ tal que os pesos dos itens não ultrapassem uma capacidade $c$ ($\sum_{i=0}^{n-1}w_i\leq c$).

Para a solução do problema por meio de um algoritmo genético foi utilizado a função objetivo da equação ref:eq:of para maximização. Essa função é uma variação da função original para penalizar soluções proporcionalmente a sua violação. O min serve para que as soluções válidas sejam simplesmente $\sum_{i=0}^{n-1} u_i$.

#+begin_export latex
\begin{equation}
\label{eq:of}
F_o(x) = \sum_{i=0}^{n-1} u_i \times min((1 - (\sum_{i=0}^{n-1}w_i - c)/c),1)
\end{equation}
#+end_export

# Esse problema claramente tem um espaço de busca de $2^n$ combinações, isso mostra que é um problema difícil  

* Solução

** Representação

Para representar o problema foi utilizado um vetor binário $s$ que indica em cada índice $i$ se o item $i$ está ou não na solução/mochila (i.e., $s\in \{False\text{(Não está na mochila)},True\text{(Está na mochila)}\}^n$).

** Seleção de pais

A estratégia de seleção de pais utilizada foi a roleta, tal que um indivíduo é selecionado a partir de um procedimento que define uma probabilidade de ser escolhido para cada indivíduo com base em seu fitness e após isso um indivíduo é escolhido a partir desse conjunto de probabilidades.

Para a atribuição das probabilidades foi atribuído para cada individuo uma probabilidade de acordo com seu rank na população.

** Cruzamento

Para a intensificação do espaço de busca foi utilizado como estratégia de cruzamento o cruzamento de ponto, tal que um valor aleatório é escolhido no intervalo $[1,n-2]$ e esse ponto irá ser utilizado para o particionamento dos pedaços do genoma para criação dos filhos.

Quando a taxa de cruzamento não é de 100% então indivíduos da população anterior são adicionados aleatoriamente a nova população até o limite de indivíduos.

** Mutação

Para mutação dos indivíduos foi utilizado um parâmetro de taxa de mutação que define a probabilidade de um gene ser mutado, a mutação é basicamente a inversão do bit.

** Elitismo

Para garantir uma curva de convergência sem oscilação e constante busca a melhorar os valores o elitismo foi aplicado e definido como a preservação do indivíduo com maior aptidão da população anterior, ele substitui um indivíduo aleatório da nova população. 

** Parâmetros

Os parâmetros mais relevantes são mostrados na tabela a seguir, através dele o algoritmo genético pode ser ajustado para obter boas soluções, cruzamento e mutação (aqui, no caso, não foram estudadas outras variações).

#+CAPTION: Parâmetros
| Parâmetro                | Descrição                                                           |
| #População               | Quantidade de indivíduos                                            |
| #Gerações                | Quantidade de gerações                                              |
| Taxa de cruzamento       | Taxa do número de indivíduos que vão cruzar                         |
| Probabilidade de mutação | Probabilidade da mutação de um gene                                 |
| Elitismo                 | Se irá usar a preservação do melhor indivíduo da população anterior |

Uma visão geral de como o algoritmo funciona é dado no algoritmo ref:alg:ag.
#+begin_export latex
\begin{algorithm}
  \caption{Algoritmo genético}
  \label{alg:ag}
  \begin{algorithmic}[1]
  \State Inicia a população com cromossomos aleatórios
  \For{$i=1$ to \#Gerações}
  \State Cruza os indivíduos utilizando a roleta para selecionar os pais e de acordo com a taxa de cruzamento
  \State Completa o número de índivíduos com indivíduos aleatórios da população anterior caso a taxa de cruzamento não seja de 100\%
  \State Faz a mutação dos indivíduos da população atual de acordo com a probabilidade de mutação
  \If{Elitismo}
  \State Seleciona o melhor indivíduo da população anterior e substitui um indíviduo aleatório da geração corrente
  \EndIf
  \EndFor
  \end{algorithmic}
\end{algorithm}
#+end_export


* Resultados

Para a análise de resultados foi utilizado 10 execuções para cada conjunto de parâmetro, devido a natureza probabilística do problema é importante sempre sumarizar os resultados de varias execuções para ter uma ideia do resultado esperado.

As instâncias utilizadas foram obtidas online\footnote{\label{fn:instances}\url{https://people.sc.fsu.edu/~jburkardt/datasets/knapsack_01/}}, todas as instâncias foram executadas e avaliadas. A tabela a seguir mostra as características das bases e um rótulo para cada uma delas.

#+CAPTION: Características das instâncias.
| Instância | #Itens | Capacidade | Utilidade ótima |
| p01       |     10 |        165 |             309 |
| p02       |      5 |         26 |              51 |
| p03       |      6 |        190 |             150 |
| p04       |      7 |         50 |             107 |
| p05       |      8 |        104 |             900 |
| p06       |      7 |        170 |            1735 |
| p07       |     15 |        750 |            1458 |
| p08       |     24 |    6404180 |        13549094 |

Espera-se que a instância p08 seja a mais complicada de se tratar pelo número de itens apresentados.
** Calibragem de parâmetros

Para o começo da análise um experimento fatorial completo será realizado em cada instância. Os valores para busca estão indicados tabela a seguir com o domínio de busca para cada parâmetro (tabela ref:tbl:hyperparameter).

#+CAPTION: Domínio de busca de cada parâmetro.
#+NAME: tbl:hyperparameter
|------------------------------------------+-------------------|
| Elitismo                                 | {False, True}     |
| #Gerações                                | {25,50,100}       |
| #População                               | {25,50,100}       |
| Taxa de cruzamento                       | {0.6, 0.8, 1.0}   |
| Probabilidade de mutação                 | {0.01, 0.05, 0.1} |
|------------------------------------------+-------------------|

Depois da execução o top-3 de parâmetros, de cada instância, são descritos na tabela ref:tbl:parameters, onde $\mu$ denota a média e $\sigma$ denota o desvio padrão das 10 execuções. Nessa tabela os dados são obtidos pela ultima geração de cada execução.

** Experimento fatorial
Primeiro, em uma visão geral, é possível ver que diversos conjuntos de parâmetros conseguiram chegar na mesma melhor solução para cada instância (não foram mostrados todos por limitação de espaço, porém em problemas pequenos até mesmo sem elitismo foi possível atingir a solução ótima), isso mostra que diversas combinações de parâmetros são viáveis para otimização desse problema quando o problema é pequeno. Também é interessante notar que diversas execuções para um mesmo conjunto de parâmetros conseguiram chegar no mesmo resultado, assim obtendo um desvio padrão de 0 para diversas soluções, mostrando resultados bem consistentes.

Nas instâncias maiores como p07 e p08 já há uma variação maior de resultados. Na instância p07 na média as execuções conseguiram valores muito próximos do ótimo e também com pequena variação entre execuções. Na instância p08 existe maior variação, porém a variação relativa a os valores é baixa, então no geral foi possível obter boas soluções para essa instância e valores bem próximos do ótimo.

Na instância p07 os melhores parâmetros estão mais relacionados com diversificação da população por meio da taxa de mutação, isso mostra que talvez pela dificuldade do problema mais diversificação foi necessária para sair de soluções "obvias". Já na instância p08 as melhores soluções na média e também com um bom grau de baixa variabilidade entre execuções está mais relacionada com intensificação no espaço de busca, também é interessante notar que quando o tamanho da população é menor a variação aumenta pois não tem indivíduos o bastante para uma população mais estável e também com uma mutação maior obviamente os resultados podem variar mais.

Em relação a aptidão média, é possível ver que nem sempre a população que tem um grande conjunto de bons indivíduos irá ser capaz de chegar na solução ótima já que na tabela temos a melhor solução do p08 com valor menor de média da aptidão média que a segunda melhor solução com o melhor individuo. Isso também é lógico pois indivíduos ruins podem compartilhar características do individuo ótimo e com isso ser vantajoso ter uma população diversa.

Pela mediana é possível ter uma ideia de que os indivíduos gerados não estavam saindo muito da linha do normal (não tinham muito outliers), isso é indicado pela baixa diferença entre média e mediana.

Um ponto do algoritmo genético utilizado é que grande parte dos indivíduos convergiram para um ponto, aptidão média próxima do melhor indivíduo, porém ainda conseguindo diversificar.


#+begin_export latex
\begin{table}
\footnotesize
\caption{Top-3 parâmetros e seus resultados.}
\label{tbl:parameters}
  \makebox[\textwidth]{
\begin{tabular}{|p{0.88cm}|l|l|l|l|l|l|l|l|l|l|l|}
%Taxa de cruzamento & \rotatebox[origin=c]{45}{Elitismo} & Probabilidade de mutação & \rotatebox[origin=c]{45}{Cruzamento} & \rotatebox[origin=c]{45}{\#Gerações} & \rotatebox[origin=c]{45}{\#População} & \multicolumn{2}{c}{Melhor aptidão} & \multicolumn{2}{|c|}{Aptidão média} & \multicolumn{2}{c|}{Aptidão mediana}\\
% & & & & & & \multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} & \multicolumn{1}{|c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} &\multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} \\
\rotatebox[origin=c]{90}{Elitismo} & \rotatebox[origin=c]{90}{\#Gerações} &\rotatebox[origin=c]{90}{\#População} &\rotatebox[origin=c]{90}{Taxa de cruzamento} & \rotatebox[origin=c]{90}{Taxa de mutação} & \rotatebox[origin=c]{90}{Instância} & \multicolumn{2}{c|}{Melhor aptidão} & \multicolumn{2}{c|}{Aptidão média} & \multicolumn{2}{c|}{Aptidão mediana}\\
 & & & & & & \multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} & \multicolumn{1}{|c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} &\multicolumn{1}{c|}{$\mu$}& \multicolumn{1}{c|}{$\sigma$} \\
True & 100.0 & 100.0 & 1.0 & 0.10 & p01 & 309.0 & 0.0 & 69.26480 & 22.901851 & 115.61425 & 20.582835\\
True & 100.0 & 50.0 & 0.8 & 0.10 & p01 & 309.0 & 0.0 & 91.11412 & 42.475184 & 133.09363 & 28.347653\\
True & 25.0 & 100.0 & 1.0 & 0.05 & p01 & 309.0 & 0.0 & 87.58990 & 28.289074 & 131.40608 & 19.603148\\
True & 50.0 & 50.0 & 0.8 & 0.05 & p02 & 51.0 & 0.0 & 37.52032 & 2.802618 & 39.91923 & 2.213124\\
True & 25.0 & 25.0 & 1.0 & 0.01 & p02 & 51.0 & 0.0 & 40.81784 & 6.731410 & 42.76924 & 8.664546\\
False & 100.0 & 100.0 & 0.8 & 0.10 & p02 & 51.0 & 0.0 & 36.66784 & 1.466509 & 39.17692 & 0.997066\\
True & 50.0 & 25.0 & 0.6 & 0.05 & p03 & 150.0 & 0.0 & 111.21108 & 9.347447 & 119.17842 & 14.004461\\
True & 100.0 & 100.0 & 1.0 & 0.05 & p03 & 150.0 & 0.0 & 110.86716 & 3.264517 & 116.00131 & 3.820061\\
True & 100.0 & 25.0 & 1.0 & 0.05 & p03 & 150.0 & 0.0 & 111.33645 & 9.440393 & 117.25262 & 12.284196\\
True & 50.0 & 50.0 & 0.8 & 0.05 & p04 & 107.0 & 0.0 & 77.40792 & 6.120049 & 85.121 & 6.774361\\
True & 50.0 & 100.0 & 0.6 & 0.05 & p04 & 107.0 & 0.0 & 71.51278 & 3.614014 & 78.874 & 5.475094\\
True & 100.0 & 100.0 & 0.8 & 0.05 & p04 & 107.0 & 0.0 & 73.81756 & 3.791986 & 79.110 & 7.153736\\
True & 100.0 & 100.0 & 1.0 & 0.10 & p05 & 900.0 & 0.0 & 629.59598 & 47.008407 & 670.70000 & 147.360706\\
True & 25.0 & 100.0 & 1.0 & 0.10 & p05 & 900.0 & 0.0 & 617.63170 & 47.627178 & 657.90000 & 126.131721\\
True & 50.0 & 25.0 & 0.8 & 0.10 & p05 & 900.0 & 0.0 & 654.87650 & 110.482456 & 721.98269 & 176.422449\\
True & 100.0 & 100.0 & 1.0 & 0.10 & p06 & 1735.0 & 0.0 & 1327.69152 & 41.518974 & 1525.81677 & 73.094893\\
True & 25.0 & 50.0 & 0.8 & 0.05 & p06 & 1735.0 & 0.0 & 1325.29779 & 41.839340 & 1482.88823 & 136.299371\\
True & 100.0 & 50.0 & 0.6 & 0.10 & p06 & 1735.0 & 0.0 & 1320.29608 & 74.306556 & 1495.51883 & 130.055311\\
True & 100.0 & 100.0 & 0.8 & 0.05 & p07 & 1456.5 & 1.433721 & 1248.48938 & 21.235654 & 1308.04413 & 19.305473\\
True & 100.0 & 100.0 & 1.0 & 0.10 & p07 & 1456.0 & 2.357023 & 1242.05123 & 25.334396 & 1308.39507 & 21.371521\\
True & 100.0 & 100.0 & 1.0 & 0.01 & p07 & 1455.8 & 2.485514 & 1226.10597 & 49.628700 & 1292.43479 & 56.868701\\
True & 100.0 & 100.0 & 1.0 & 0.01 & p08 & 13417058.6 & 41823.931632 & 1.177373e+07 & 429067.162976 & 1.226555e+07 & 356532.597135\\
True & 100.0 & 50.0 & 1.0 & 0.01 & p08 & 13399101.2 & 55809.090012 & 1.204174e+07 & 363525.118502 & 1.250030e+07 & 309185.395593\\
True & 100.0 & 100.0 & 1.0 & 0.10 & p08 & 13388607.2 & 61308.331152 & 1.145437e+07 & 246327.637650 & 1.203371e+07 & 227051.466012\\
\end{tabular}
}
\end{table}
#+end_export

** Análise das melhores soluções

Também é importante analisar os parâmetros indivídualmente (suas execuções) para entender possíveis situações e seus comportamentos. As instâncias mais difíceis serão análisadas.


*** Instância p07

Na figura ref:fig:best_executions1 é confirmado que a média realmente está estavel pois a sua linha acompanha a médiana, logo poucos indíviduos são modificados ao ponto de serem completos outliers (o que aparenta ser uma caracteristica da instância e no geral na maioria delas, pois é dificil encontrar uma instância no qual um item tem muita discrepância dos outros). O valor próximo do ótimo é encontrado rapidamente, porém a dificuldade é em achar a solução ótima. Já a pior aptidão não se mostra tão discrepante como em outros problemas, porém como esporadicamente mutação é aplicada então indivíduos sofrem piora e a curva se torna assim. Também é importante lembrar que essa é a média de varias execuções logo a linha da pior aptidão não descreve o comportamento de uma execução por si só.

Outro ponto a se notar na figura ref:fig:best_executions1 é que as execuções não tem convergência rapida como em outros problemas, o que demonstra a dificuldade dessa instância e problema, porém em algumas execuções (7 e 10) é possível observar que há uma rápida convergência, isso ressalta a natureza estocástica dos algoritmos genéticos.

# Os parâmetros serão representados por uma tupla para identificação e os elementos estão na ordem das colunas da tabela.

# No gráfico a seguir (figura ref:fig:best_executions1) é possível observar que a alta probabilidade de mutação faz com que seja muito provável que exista um indivíduo com uma aptidão muito ruim. Com um número maior de genes talvez esse peso na mutação de um só gene pode ser diluido e não haja tanta variação. Isso mostra que é importante utilizar a mediana como métrica de avaliação para saber o verdadeiro valor que descreve a maior parte dos indivíduos. As varias execuções possuem diferentes começos, algumas minimizam muito rapidamente inicialmente e outras não, porém além desse ponto é indistinguível.
#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_0.8_elitism_True_mutation_rate_0.05_eid_1_instance_name_p07_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_0.8_elitism_True_mutation_rate_0.05_eid_10_instance_name_p07_multiple_executions.eps}
	\caption{Execuções do melhor conjunto de parâmetros da instância p07.}
	\label{fig:best_executions1}
\end{figure}
#+end_export

Na figura ref:fig:best_executions2 há uma diferença em relação ao melhor conjunto de parâmetros que devido ao aumento na taxa de mutação mais indíviduos piores são gerados, porém mais diversificação ocorreu, e no geral todas execuções parecem ter uma convergência mais lenta e as execuções são mais discrepantes (como era de se esperar), o que pode indicar que para esse problema mais intensificação é importante para uma convergência rápida. Ao mesmo tempo que a convergência parece ser mais lenta, mais mudanças de melhora parecem ocorrer nas gerações, porém não rápidas o suficiente.

#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.1_eid_1_instance_name_p07_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.1_eid_10_instance_name_p07_multiple_executions.eps}
	\caption{Execuções do segundo melhor conjunto de parâmetros da instância p07.}
	\label{fig:best_executions2}
\end{figure}
#+end_export

Na figura ref:fig:best_executions3 há mais intensificação e isso pode ser visto pelo aproximamento da aptidão média e a aptidão mediana, também rapidamente algumas soluções convergem. O problema desse conjunto de parâmetro é que para essa instância diversificação é necessária para sair do plato de soluções proximas da ótima.

#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_1_instance_name_p07_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_10_instance_name_p07_multiple_executions.eps}
	\caption{Execuções do terceiro melhor conjunto de parâmetros da instância p07.}
	\label{fig:best_executions3}
\end{figure}
#+end_export

*** Instância p08
A instância p08 apresentou uma grande dificuldade pelo seu espaço de busca grande. Na figura ref:fig:best_executions4 fica claro que a instensificação foi priorizada no melhor conjunto de parâmetros já que a aptidão média e mediana estão bem proximas. Como essa instância é grande a convergência foi bem lenta, porém a intensificação nesse espaço de busca se mostrou a melhor escolha.

#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_1_instance_name_p08_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_10_instance_name_p08_multiple_executions.eps}
	\caption{Execuções do melhor conjunto de parâmetros da instância p08.}
	\label{fig:best_executions4}
\end{figure}
#+end_export

A figura ref:fig:best_executions5 mostra o segundo melhor conjunto de parâmetros, não muito diferente da melhor solução somente com um tamanho menor da população. Várias carácteristicas do melhor conjunto de parâmetros ainda estão presentes, porém a pior aptidão é maior durante as gerações o que mostra que os indíviduos estão todos bem próximos em relação a solução (uma característica de população pequena, muito cruzamento e pouca mutação). A variação na população também parece ser mais rápida no começo, isso pode se dever a intensificação muito forte de um grupo seleto de indíviduos.

#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_50_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_1_instance_name_p08_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_50_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.01_eid_10_instance_name_p08_multiple_executions.eps}
	\caption{Execuções do segundo melhor conjunto de parâmetros da instância p08.}
	\label{fig:best_executions5}
\end{figure}
#+end_export
Na figura ref:fig:best_executions6 há mais outliers visivelmente, porém a manutenção da população ainda consegue se manter já que o número de indíviduos e alto e há da mais estabilidade na população no geral. As execuções tem uma convergência de maneira bem igual, não há muita variação entre as execuções no começo.
#+begin_export latex
\begin{figure}[H]
	\centering
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.1_eid_1_instance_name_p08_mean_and_median_and_best.eps}
	\includegraphics[scale=0.5]{../img/mutation_policy_InvertBit_cross_policy_CrossPoint_selection_policy_RankRoulette_num_pop_100_num_generations_100_cross_rate_1.0_elitism_True_mutation_rate_0.1_eid_10_instance_name_p08_multiple_executions.eps}
	\caption{Execuções do terceiro melhor conjunto de parâmetros da instância p08.}
	\label{fig:best_executions6}
\end{figure}
#+end_export

*** Análise detalhada de uma solução

Para ter uma ideia de como o algoritmo está se comportando mais detalhadamente será feito a análise dos valores a cada geração atráves de uma tabela. Foi escolhido o parâmetro (1.0,True,0.01,$BLX\text{-}\alpha\beta$,50,50) por questão de espaço e também por possuir características de soluções ótimas.

O primeiro ponto que se nota na execução, na tabela ref:tbl:execution, é que a convergência é consistente. A média possui grande pertubação ao longo do tempo e não é muito consistente, as vezes próxima do melhor indivíduo e as vezes muito longe. A mediana é muito mais robusta e permanece consistente.

É possível ver também que nessa execução após a geração 37 o algoritmo ficou em uma situação que não conseguia melhorar a solução e enquanto isso mais indivíduos são mutados para diversificar a população, pois ficou muito estável.

#+begin_export latex
\begin{table}
\footnotesize
\center
\caption{Execução do conjunto de parâmetros (1.0,True,0.01,$BLX\text{-}\alpha\beta$,50,50)}\label{tbl:execution}
\begin{tabular}{rrrrr}
Geração & Melhor aptidão & Aptidão média & Aptidão mediana & Pior aptidão\\
1 & 3.03 & 5.737 & 5.922 & 7.774\\
2 & 2.7 & 4.921 & 5.003 & 7.598\\
3 & 1.355 & 4.357 & 4.212 & 7.542\\
4 & 0.9532 & 4.16 & 4.094 & 7.453\\
5 & 0.4438 & 3.26 & 3.252 & 6.557\\
6 & 0.4438 & 2.698 & 2.808 & 6.572\\
7 & 0.05584 & 1.456 & 1.223 & 6.475\\
8 & 0.03137 & 0.8548 & 0.4438 & 5.768\\
9 & 0.02333 & 0.2106 & 0.1202 & 1.005\\
10 & 0.006422 & 0.2036 & 0.06973 & 4.418\\
11 & 0.001464 & 0.04493 & 0.03404 & 0.3647\\
12 & 0.0006806 & 0.0204 & 0.01673 & 0.05888\\
13 & 0.0002826 & 0.06061 & 0.003686 & 2.795\\
14 & 0.0001527 & 0.002015 & 0.0009366 & 0.02844\\
15 & 4.531e-05 & 0.0006747 & 0.0004846 & 0.002932\\
16 & 1.212e-05 & 0.09815 & 0.0002627 & 4.892\\
17 & 6.287e-06 & 9.305e-05 & 4.95e-05 & 0.0006566\\
18 & 1.183e-06 & 3.243e-05 & 2.314e-05 & 9.813e-05\\
19 & 2.919e-07 & 1.215e-05 & 9.87e-06 & 5.692e-05\\
20 & 1.318e-07 & 0.07487 & 1.728e-06 & 3.743\\
21 & 1.068e-07 & 6.001e-07 & 3.196e-07 & 3.501e-06\\
22 & 6.862e-08 & 0.0006822 & 2.023e-07 & 0.03409\\
23 & 1.097e-08 & 0.03735 & 1.584e-07 & 1.868\\
24 & 7.703e-09 & 1.036e-07 & 8.475e-08 & 3.687e-07\\
25 & 3.937e-09 & 4.251e-08 & 3.559e-08 & 1.528e-07\\
26 & 1.466e-09 & 0.005874 & 8.875e-09 & 0.2937\\
27 & 9.642e-10 & 0.07869 & 4.483e-09 & 3.935\\
28 & 6.333e-10 & 3.304e-09 & 2.914e-09 & 1.186e-08\\
29 & 2.241e-10 & 2.449e-09 & 1.803e-09 & 8.26e-09\\
30 & 1.979e-10 & 1.315e-09 & 1.038e-09 & 4.441e-09\\
31 & 1.43e-10 & 0.05931 & 3.948e-10 & 2.965\\
32 & 6.977e-11 & 0.09286 & 2.26e-10 & 4.643\\
33 & 4.417e-11 & 2.183e-10 & 2.154e-10 & 6.029e-10\\
34 & 1.2e-11 & 1.676e-10 & 1.509e-10 & 7.18e-10\\
35 & 1.2e-11 & 0.06896 & 9.304e-11 & 3.448\\
36 & 1.2e-11 & 5.623e-11 & 4.657e-11 & 1.592e-10\\
37 & 2.989e-13 & 0.08737 & 2.948e-11 & 4.369\\
38 & 2.989e-13 & 7.709e-12 & 3.423e-12 & 4.182e-11\\
39 & 2.989e-13 & 3.393e-13 & 2.989e-13 & 1.784e-12\\
40 & 2.989e-13 & 0.09909 & 2.989e-13 & 4.954\\
41 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
42 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
43 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
44 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
45 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
46 & 2.989e-13 & 0.02359 & 2.989e-13 & 1.18\\
47 & 2.989e-13 & 0.0516 & 2.989e-13 & 2.58\\
48 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
49 & 2.989e-13 & 0.06502 & 2.989e-13 & 3.251\\
50 & 2.989e-13 & 2.989e-13 & 2.989e-13 & 2.989e-13\\
\end{tabular}
\end{table}
#+end_export


# \begin{tabular}{lrrr}
# Month & \multicolumn{1}{c}{Days} & Nr.\ sold & per day\\
# % BEGIN RECEIVE ORGTBL salesfigures
# % END RECEIVE ORGTBL salesfigures
# \end{tabular}
# %
# \begin{comment}
# #+ORGTBL: SEND salesfigures orgtbl-to-latex :splice t :skip 2
# | Month | Days | Nr sold | per day |
# |-------+------+---------+---------|
# | Jan   |   23 |      55 |     2.4 |
# | Feb   |   21 |      16 |     0.8 |
# | March |   22 |     278 |    12.6 |
# #+TBLFM: $4=$3/$2;%.1f
# \end{comment}

# \begin{tabular}{lrrr}
# Month & \multicolumn{1}{c}{Days} & Nr.\ sold & per day\\
# % BEGIN RECEIVE ORGTBL salesfigures
# % END RECEIVE ORGTBL salesfigures
# \end{tabular}
# %
# \begin{comment}
# #+ORGTBL: SEND salesfigures orgtbl-to-latex
# #+EXPORT: table2.org
# \end{comment}

* Conclusão

Com esse trabalho foi possível fazer a análise detalhada do comportamento de um modelo de algoritmo genético. Atráves de multiplos gráficos os parâmetros do modelo foram análisados. Como o problema a ser tratado é bem simples o algoritmo majoritariamente consegue achar o ponto ótimo do domínio, porém é interessante ver que mesmo com o espaço de busca foi bem maior em relação ao trabalho com a representação binária a convergência (para a solução ótima) foi mais rápida (nos casos que a representação binária utiliza muitos bits). 

Foi interessante notar que varias execuções podem começar de pontos diferentes e cada uma ter soluções finais bastante diferentes (mesmo que pouco no valor, porém visualmente parecem bastante).

Com a representação real também foi possível ter mais métodos para intensificar a busca, como por exemplo nos operadores de cruzamentos ($BLX\text{-}\alpha$ e $BLX\text{-}\alpha\beta$), que são métodos que apresentam uma busca consistente em direção a bons indivíduos, com a representação binária o cruzamento era mais cego e não conseguia direcionar a busca com mais objetivo.

Outro ponto também é que na representação binária a seleção de pais realizada era era mais aleatória que voltada para uma intensificação na busca (priorizar os melhores) comparada ao método utilizado agora de roleta.

Um ponto que a representação real não apresenta é a separação de um gene em partes, porém de certa forma tenta fazer isso através de um intervalo de busca. É interessante notar que se a representação binária fosse transformada de volta em um número real poderia ser aplicado todos métodos apresentados aqui, porém com um espaço de busca variável, mas teria o custo nas transformações de bases.



bibliography:doc.bib
bibliographystyle:plain
